/**
 * Verified list of Barcelona nightlife places (clubs, discotecas, concert
 * halls and event spaces). It replaces every previously imported venue.
 *
 * Rules (see docs/event-discovery.md):
 * - Every entry was checked against its official site and at least one
 *   independent source listing activity in 2026 (`sources`).
 * - Only facts found in those sources are written here. Anything else stays
 *   out: coordinates, barrio and district come from OpenStreetMap (Nominatim)
 *   for the address; photos, Instagram, hours and price range come from the
 *   official website at each sync, never typed by hand.
 * - `status` is the state verified on `verifiedAt`. Closed places are not
 *   listed (see EXCLUDED for the ones that were checked and left out).
 */
export type CuratedType = "DISCO" | "CLUB" | "CONCERT_HALL" | "EVENT_SPACE" | "FESTIVAL_SPACE" | "OTHER";

export interface CuratedVenue {
  /** Stable id (also the venue slug). */
  key: string;
  name: string;
  type: CuratedType;
  /** Street address as published by the venue. */
  address: string;
  /** Municipality (Barcelona unless stated). */
  municipality?: string;
  /** Free-form geocoding query when the street address is shared by several places. */
  geocodeQuery?: string;
  description: string;
  /** Music styles and kinds of event. */
  music: string[];
  /** Official website (omitted when the place has none that could be confirmed). */
  website?: string;
  /** Other pages with a photo of the place (JSON-LD / og:image), used when the official site has none. */
  photoPages?: string[];
  /** Only when confirmed as the official account; otherwise read from the official site. */
  instagram?: string;
  /** Former names and rooms, used to match events from ticketing sites. */
  aliases?: string[];
  /** Extra official pages with the agenda (JSON-LD events), besides the home page. */
  agendaUrls?: string[];
  status: "OPEN" | "TEMPORARILY_CLOSED" | "PERMANENTLY_CLOSED";
  verifiedAt: string;
  sources: string[];
}

const V = "2026-09-30";

export const BARCELONA_VENUES: CuratedVenue[] = [
  // ─── Clubs y discotecas ────────────────────────────────────────────────────
  {
    key: "razzmatazz",
    name: "Razzmatazz",
    type: "CLUB",
    address: "Carrer dels Almogàvers, 122",
    description: "Antigua fábrica del Poblenou convertida en club y sala de conciertos, con cinco salas de música distintas.",
    music: ["Conciertos", "Indie", "Electrónica", "Techno", "Pop"],
    website: "https://www.salarazzmatazz.com/",
    aliases: ["Sala Razzmatazz", "Razzmatazz 1", "Razzmatazz 2", "Razzmatazz 3", "The Loft", "Lolita"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.salarazzmatazz.com/en/", "https://en.wikipedia.org/wiki/Razzmatazz_(club)", "https://ra.co/clubs/911"],
  },
  {
    key: "opium-barcelona",
    name: "Opium Barcelona",
    type: "DISCO",
    address: "Passeig Marítim de la Barceloneta, 34",
    description: "Restaurante y discoteca en primera línea de playa, junto al Port Olímpic, con DJs internacionales.",
    music: ["Comercial", "House", "Reggaeton"],
    website: "https://opiumbarcelona.com/",
    instagram: "opiumbarcelona",
    aliases: ["Opium"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://opiumbarcelona.com/en/", "https://www.nightlifeinternational.org/en/members/item/4434-opium-barcelona"],
  },
  {
    key: "shoko-barcelona",
    name: "Shôko Barcelona",
    type: "DISCO",
    address: "Passeig Marítim de la Barceloneta, 36",
    description: "Restaurante y club frente al mar en el Port Olímpic, con terraza y pista de baile.",
    music: ["House", "Comercial"],
    website: "https://shoko.biz/",
    aliases: ["Shoko", "Shôko"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://shoko.biz/", "https://www.barcelona-tourist-guide.com/en/club/shoko-club-barcelona.html"],
  },
  {
    key: "sutton-barcelona",
    name: "Sutton Barcelona",
    type: "DISCO",
    address: "Carrer de Tuset, 13",
    description: "Discoteca de la zona alta abierta desde 2001, con código de vestimenta.",
    music: ["Comercial", "Reggaeton", "Hip Hop"],
    website: "https://www.thesuttonclub.com/",
    aliases: ["Sutton", "Sutton The Club", "Sutton Club"],
    photoPages: ["https://xceed.me/en/barcelona/venue/sutton-barcelona"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.thesuttonclub.com/en/", "https://xceed.me/en/barcelona/venue/sutton-barcelona"],
  },
  {
    key: "moog",
    name: "Moog",
    type: "CLUB",
    address: "Carrer de l'Arc del Teatre, 3",
    description: "Club pequeño junto a la Rambla, referencia del techno en la ciudad desde 1996, con una segunda sala (Villa Rosa) de pop y disco.",
    music: ["Techno", "Electrónica", "Pop", "Disco"],
    website: "https://www.masimas.com/moog",
    aliases: ["Moog Club", "Moog Barcelona"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.masimas.com/moog", "https://www.barcelona-tourist-guide.com/en/club/moog-club-barcelona.html"],
  },
  {
    key: "sala-apolo",
    name: "Sala Apolo",
    type: "CONCERT_HALL",
    address: "Carrer Nou de la Rambla, 113",
    description: "Uno de los salones de baile más antiguos de Europa: conciertos y sesiones de club en el Paral·lel.",
    music: ["Conciertos", "Electrónica", "Indie", "Fiestas"],
    website: "https://www.sala-apolo.com/",
    aliases: ["Apolo", "Sala Apolo Barcelona"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.nightlifeinternational.org/en/members/item/4442-sala-apolo-barcelona", "https://www.sala-apolo.com/en/clubs/nitsa"],
  },
  {
    key: "la-2-de-apolo",
    name: "La 2 de Apolo",
    type: "CONCERT_HALL",
    address: "Carrer Nou de la Rambla, 113",
    geocodeQuery: "Sala Apolo, Carrer Nou de la Rambla 113, Barcelona",
    description: "Segunda sala de Apolo, para unas 400 personas: conciertos y fiestas.",
    music: ["Conciertos", "Fiestas"],
    website: "https://www.sala-apolo.com/",
    aliases: ["La [2] de Apolo", "La 2 Apolo", "Sala 2 Apolo", "La (2) de Apolo"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.ticketmaster.es/venue/la-2-de-apolo-barcelona-/slapol2bcn/114", "https://www.themusicrepublic.es/locations/sala-apolo-2/"],
  },
  {
    key: "nitsa-club",
    name: "Nitsa Club",
    type: "CLUB",
    address: "Carrer Nou de la Rambla, 113",
    geocodeQuery: "Sala Apolo, Carrer Nou de la Rambla 113, Barcelona",
    description: "Club de música electrónica que se celebra en Sala Apolo los viernes y sábados desde 1996.",
    music: ["Techno", "Electro", "House", "Drum and bass"],
    website: "https://www.sala-apolo.com/en/clubs/nitsa",
    aliases: ["Nitsa", "Nitsa Apolo"],
    photoPages: ["https://xceed.me/en/barcelona/venue/nitsa-club"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.sala-apolo.com/en/clubs/nitsa", "https://xceed.me/en/barcelona/venue/nitsa-club"],
  },
  {
    key: "city-hall-barcelona",
    name: "City Hall Barcelona",
    type: "CLUB",
    address: "Rambla de Catalunya, 2-4",
    description: "Club en un antiguo teatro del siglo XIX junto a plaza de Catalunya: techno, house y noches temáticas.",
    music: ["Techno", "House", "Urbano", "Latino"],
    website: "https://www.cityhallbarcelona.com/",
    aliases: ["City Hall"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.cityhallbarcelona.com/en-us", "https://thegaypassport.com/venue/disco-city-hall/"],
  },
  {
    key: "otto-zutz",
    name: "Otto Zutz",
    type: "DISCO",
    address: "Carrer de Lincoln, 15",
    description: "Discoteca de tres plantas en una antigua fábrica textil, abierta desde 1985.",
    music: ["Hip Hop", "Reggaeton", "House", "Comercial"],
    website: "https://en.ottozutz.com/",
    instagram: "ottozutzclub",
    aliases: ["Otto Zutz Club", "Otto Zutz Barcelona"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://en.ottozutz.com/", "https://www.barcelona-tourist-guide.com/en/club/otto-zutz-club-barcelona.html"],
  },
  {
    key: "macarena-club",
    name: "Macarena Club",
    type: "CLUB",
    address: "Carrer Nou de Sant Francesc, 5",
    description: "Pequeño club del Gòtic dedicado a la electrónica underground desde 2001.",
    music: ["House", "Techno", "Electrónica"],
    website: "http://macarenaclub.com/",
    aliases: ["Macarena", "Macarena Club Barcelona"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://guia.barcelona.cat/es/detall/bar-musical-macarena-club_75990094018.html", "https://www.songkick.com/venues/1495633-macarena-club-barcelona"],
  },
  {
    key: "hyde-club",
    name: "Hyde Club",
    type: "DISCO",
    address: "Passatge de Domingo, 3",
    description: "Discoteca del Eixample, muy cerca de passeig de Gràcia.",
    music: ["Comercial", "Fiestas"],
    website: "http://www.hydebcn.com/",
    aliases: ["Hyde", "Hyde Barcelona", "Hyde Club Barcelona"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://guia.barcelona.cat/es/detall/discoteca-hyde-club_99400476312.html", "https://www.yelp.com/biz/hyde-club-barcelona-2"],
  },
  {
    key: "bling-bling-barcelona",
    name: "Bling Bling Barcelona",
    type: "DISCO",
    address: "Carrer de Tuset, 8-10",
    description: "Discoteca de varias plantas en Tuset, del Grupo Costa Este.",
    music: ["House", "Hip Hop", "Reggaeton", "Comercial"],
    website: "https://www.blingblingbcn.com/",
    aliases: ["Bling Bling"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://grupocostaeste.com/en/club/bling-bling/", "https://www.yelp.com/biz/bling-bling-barcelona"],
  },
  {
    key: "ku-barcelona",
    name: "Ku Barcelona",
    type: "DISCO",
    address: "Passeig Marítim de la Barceloneta, 38",
    description: "Club y restaurante frente a la playa del Port Olímpic. Antes Pacha Barcelona: cambió de nombre en septiembre de 2025.",
    music: ["House", "Techno", "Reggaeton", "Comercial"],
    website: "https://www.kubarcelona.com/",
    instagram: "kubarcelonaclub",
    aliases: ["Pacha Barcelona", "Pacha", "Ku", "KU Barcelona"],
    status: "OPEN",
    verifiedAt: V,
    sources: [
      "https://www.kubarcelona.com/",
      "https://cronicaglobal.elespanol.com/business/20250918/pacha-barcelona-cambia-identidad-ku-iconico-ibiza/1003742689801_0.html",
      "https://grupocostaeste.com/en/club/ku-barcelona/",
    ],
  },
  {
    key: "cdlc-barcelona",
    name: "CDLC Barcelona",
    type: "DISCO",
    address: "Passeig Marítim de la Barceloneta, 32",
    description: "Carpe Diem Lounge Club: restaurante que a partir de medianoche se convierte en club, frente al mar.",
    music: ["House", "Comercial"],
    website: "https://cdlcbarcelona.com/",
    aliases: ["Carpe Diem", "Carpe Diem Lounge Club", "CDLC"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://cdlcbarcelona.com/eng/", "https://www.nightlifeinternational.org/en/news/item/4435-carpe-diem-lounge-club"],
  },
  {
    key: "sala-plataforma",
    name: "Sala Plataforma",
    type: "DISCO",
    address: "Carrer Nou de la Rambla, 145",
    description: "Sala de aire industrial en el Poble-sec con sesiones de DJ y conciertos.",
    music: ["80s", "90s", "Funk", "Indie", "Reggaeton", "Conciertos"],
    website: "http://www.salaplataforma.com/",
    aliases: ["Plataforma"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.barcelona.cat/mobilitat/en/detall/sala-plataforma_75990174460", "https://youbarcelona.com/en/club/sala-plataforma-barcelona"],
  },
  {
    key: "m7-club",
    name: "M7 Club",
    type: "CLUB",
    address: "Carrer de Mèxic, 7",
    description: "Club de techno de inspiración berlinesa cerca de plaza d'Espanya.",
    music: ["Techno", "Hard techno", "Electro", "Acid house"],
    website: "https://m7club.net/",
    aliases: ["The Club M7", "M7 Club Barcelona", "M7"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://guia.barcelona.cat/es/detall/sala-the-club-m7_99400119229.html", "https://www.nitbcn.com/en/m7-club"],
  },
  {
    key: "draco-disco-club",
    name: "Draco Disco Club",
    type: "DISCO",
    address: "Carrer de l'Alegre de Dalt, 55",
    description: "Discoteca de música latina en la zona de Gràcia.",
    music: ["Latino", "Reggaeton"],
    photoPages: ["https://xceed.me/en/barcelona/venue/draco-club"],
    aliases: ["Draco", "Draco Club", "Draco Premium Club"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://xceed.me/en/barcelona/venue/draco-club", "https://www.paginasamarillas.es/f/barcelona/draco-disco-club_236927521_000000001.html"],
  },
  {
    key: "la-biblio",
    name: "La Biblio",
    type: "DISCO",
    address: "Carrer de Moià, 1",
    description: "Discoteca de la zona alta con decoración de biblioteca.",
    music: ["House", "Deep house", "Comercial"],
    website: "https://labibliobcn.com/",
    aliases: ["La Biblio BCN", "La Biblio Barcelona"],
    photoPages: ["https://xceed.me/es/barcelona/venue/la-biblio-bcn"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://xceed.me/es/barcelona/venue/la-biblio-bcn", "https://youbarcelona.com/es/discoteca/la-biblio-club-barcelona"],
  },
  {
    key: "input-barcelona",
    name: "INPUT High Fidelity Dance Club",
    type: "CLUB",
    address: "Avinguda de Francesc Ferrer i Guàrdia, 13",
    geocodeQuery: "Poble Espanyol, Barcelona",
    description: "Club del Poble Espanyol con sonido Funktion-One y pantallas LED, abierto los fines de semana.",
    music: ["Techno", "House"],
    website: "https://inputbcn.com/",
    instagram: "inputdanceclub",
    aliases: ["INPUT", "Input Barcelona", "Input High Fidelity Club", "INPUT High Fidelity"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://inputbcn.com/", "https://ra.co/guides/clubs-in-barcelona"],
  },
  {
    key: "laut",
    name: "LAUT",
    type: "CLUB",
    address: "Carrer de Vila i Vilà, 63",
    description: "Club pequeño del Poble-sec, abierto en 2017, dedicado a la electrónica y a los sets de toda la noche.",
    music: ["Techno", "House", "Trance", "Electro", "Bass"],
    website: "https://laut.es/",
    instagram: "lautbarcelona",
    aliases: ["Laut Barcelona", "Sala Laut"],
    photoPages: ["https://xceed.me/en/barcelona/venue/laut"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://es.ra.co/clubs/129273", "https://xceed.me/en/barcelona/venue/laut"],
  },
  {
    key: "jamboree",
    name: "Jamboree",
    type: "CLUB",
    address: "Plaça Reial, 17",
    description: "Club de jazz de la plaça Reial desde 1960: conciertos a primera hora y sesión de baile después.",
    music: ["Jazz", "Blues", "Conciertos", "Hip Hop", "Funk"],
    website: "https://jamboreejazz.com/",
    aliases: ["Jamboree Jazz", "Jamboree Jazz Club", "Jamboree Barcelona"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.songkick.com/venues/204973-jamboree-jazz-club", "https://thisisbarcelona.com/music-and-festivals/concert-venues/jamboree"],
  },
  {
    key: "club-sauvage",
    name: "Club Sauvage",
    type: "CLUB",
    address: "Plaça Reial, 7",
    description: "Antes Sidecar Factory Club: el mismo local de la plaça Reial, renovado, con conciertos y sesiones de club.",
    music: ["Indie", "Conciertos", "Fiestas"],
    website: "https://sidecar.es/",
    instagram: "clubsauvage_bcn",
    aliases: ["Sidecar", "Sidecar Factory Club", "Sidecar Barcelona", "Sauvage"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.barcelona-metropolitan.com/locations/club-sauvage/", "https://sidecar.es/en/info/", "https://www.nitbcn.com/en/club-sauvage"],
  },
  {
    key: "arena-xperience",
    name: "Arena Xperience",
    type: "DISCO",
    address: "Ronda de Sant Pere, 21",
    description: "El club LGTBIQ+ más grande de Barcelona, heredero de Arena Madre y Arena Classic, con dos salas (Madre y Classic).",
    music: ["Pop", "Comercial", "Shows drag"],
    website: "https://grupoarena.com/",
    aliases: ["Arena Experience", "Arena", "Arena Madre", "Arena Classic", "Arena Sala Classic"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.timeout.es/barcelona/es/gay-y-lesbico/arena-xperience", "https://guia.barcelona.cat/es/detall/discoteca-arena-xperience_99400698702.html"],
  },
  {
    key: "sala-upload",
    name: "Sala Upload",
    type: "CONCERT_HALL",
    address: "Avinguda de Francesc Ferrer i Guàrdia, 13",
    geocodeQuery: "Poble Espanyol, Barcelona",
    description: "Sala de conciertos para 500 personas dentro del Poble Espanyol.",
    music: ["Conciertos", "Indie", "Rock"],
    website: "https://sala-upload.com/",
    aliases: ["Upload", "Sala Upload Poble Espanyol", "Sala Upload - Poble Espanyol"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://guia.barcelona.cat/es/detall/sala-upload-poble-espanyol_99400319043.html", "https://www.songkick.com/venues/4378497-sala-upload"],
  },
  {
    key: "wolf-barcelona",
    name: "Wolf Barcelona",
    type: "DISCO",
    address: "Carrer dels Almogàvers, 88",
    description: "Discoteca de más de 600 m² en el Poblenou.",
    music: ["Comercial", "Fiestas"],
    website: "http://wolfbarcelona.com/",
    aliases: ["Wolf", "Wolf BCN"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://guia.barcelona.cat/es/detall/discoteca-wolf-barcelona_95327105318.html", "https://www.timeout.es/barcelona/es/clubs/wolf-barcelona"],
  },
  {
    key: "bikini-barcelona",
    name: "Bikini Barcelona",
    type: "CONCERT_HALL",
    address: "Avinguda Diagonal, 547",
    description: "Sala de conciertos y discoteca en L'Illa Diagonal, con historia desde 1953.",
    music: ["Conciertos", "Comercial", "Fiestas"],
    website: "https://bikinibcn.com/",
    aliases: ["Sala Bikini", "Bikini"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.songkick.com/venues/36918-sala-bikini", "https://www.ticketmaster.es/venue/sala-bikini-barcelona-entradas/slbikinbcn/114"],
  },
  {
    key: "luz-de-gas",
    name: "Luz de Gas",
    type: "CONCERT_HALL",
    address: "Carrer de Muntaner, 246",
    description: "Sala de conciertos y club en un antiguo teatro de estilo rococó.",
    music: ["Conciertos", "Fiestas", "Tributos"],
    website: "http://www.luzdegas.com/",
    aliases: ["Sala Luz de Gas"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://guia.barcelona.cat/es/detall/luz-de-gas_75990090931.html", "https://www.taquilla.com/barcelona/sala-luz-de-gas-barcelona"],
  },

  // ─── Salas y espacios de eventos ───────────────────────────────────────────
  {
    key: "palau-sant-jordi",
    name: "Palau Sant Jordi",
    type: "EVENT_SPACE",
    address: "Passeig Olímpic, 5-7",
    geocodeQuery: "Palau Sant Jordi, Barcelona",
    description: "Pabellón olímpico de Montjuïc para grandes conciertos y espectáculos.",
    music: ["Conciertos", "Grandes eventos"],
    website: "https://palausantjordi.barcelona/",
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://palausantjordi.barcelona/en/events", "https://en.wikipedia.org/wiki/Palau_Sant_Jordi"],
  },
  {
    key: "sant-jordi-club",
    name: "Sant Jordi Club",
    type: "CONCERT_HALL",
    address: "Passeig Olímpic, 5-7",
    geocodeQuery: "Sant Jordi Club, Barcelona",
    description: "Sala anexa al Palau Sant Jordi para conciertos de formato medio.",
    music: ["Conciertos"],
    website: "https://palausantjordi.barcelona/",
    aliases: ["Sala Sant Jordi Club"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://guia.barcelona.cat/es/detall/palau-sant-jordi-sala-sant-jordi-club_98168154622.html", "https://www.songkick.com/venues/509546-sant-jordi-club"],
  },
  {
    key: "parc-del-forum",
    name: "Parc del Fòrum",
    type: "FESTIVAL_SPACE",
    address: "Plaça del Fòrum, 1",
    geocodeQuery: "Parc del Fòrum, Barcelona",
    description: "Recinto al aire libre junto al mar donde se celebran Primavera Sound, Cruïlla y Brunch Electronik.",
    music: ["Festivales", "Conciertos", "Electrónica"],
    website: "https://parcdelforum.barcelona/",
    aliases: ["Fòrum", "Parc del Forum", "Recinte del Fòrum"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://parcdelforum.barcelona/en", "https://en.wikipedia.org/wiki/Primavera_Sound_2026", "https://guia.barcelona.cat/en/detall/festival-cruilla-bcn_99400209139.html"],
  },
  {
    key: "poble-espanyol",
    name: "Poble Espanyol",
    type: "FESTIVAL_SPACE",
    address: "Avinguda de Francesc Ferrer i Guàrdia, 13",
    geocodeQuery: "Poble Espanyol, Barcelona",
    description: "Recinto de Montjuïc con conciertos, festivales y las Noches en Vivo de verano.",
    music: ["Conciertos", "Festivales", "Fiestas"],
    website: "https://poble-espanyol.com/",
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://poble-espanyol.com/noches-en-vivo-3/", "https://es.ra.co/clubs/41595"],
  },
  {
    key: "fira-gran-via",
    name: "Fira Barcelona Gran Via",
    type: "EVENT_SPACE",
    address: "Avinguda de Joan Carles I, 64",
    municipality: "L'Hospitalet de Llobregat",
    geocodeQuery: "Fira Gran Via, L'Hospitalet de Llobregat",
    description: "Recinto ferial de L'Hospitalet; en 2026 acoge todo el Sónar, de día y de noche.",
    music: ["Festivales", "Electrónica"],
    website: "https://www.firabarcelona.com/",
    aliases: ["Fira Gran Via", "Recinte Gran Via", "Fira de Barcelona Gran Via"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://www.segre.com/es/cultura/260619/sonar-llena-electronica-recinto-fira-gran-via-barcelona_1247612.html", "https://www.timeout.es/barcelona/es/musica/sonar-guia-completa"],
  },
  {
    key: "parallel-62",
    name: "Paral·lel 62",
    type: "CONCERT_HALL",
    address: "Avinguda del Paral·lel, 62",
    description: "Sala abierta en 2022 en el antiguo edificio de BARTS: conciertos, fiestas y espectáculos, con la sala pequeña Club 62.",
    music: ["Conciertos", "Fiestas"],
    website: "https://paral-lel62.cat/",
    aliases: ["Sala Paral·lel 62", "Paral-lel 62", "Parallel 62", "Sala Barts", "BARTS", "Club 62"],
    status: "OPEN",
    verifiedAt: V,
    sources: ["https://es.wikipedia.org/wiki/Paral%C2%B7lel_62", "https://www.barcelona.cat/metropolis/es/detall/sala-paral-lel-62_99400249050"],
  },
];

/** Checked and left out, with the reason (shown to staff, never on the map). */
export const EXCLUDED: Array<{ name: string; reason: string; sources: string[] }> = [
  { name: "Pacha Barcelona", reason: "Ahora se llama Ku Barcelona (mismo local).", sources: ["https://youbarcelona.com/es/blog/pacha-barcelona-ahora-es-ku-barcelona"] },
  { name: "Sidecar Factory Club", reason: "Ahora es Club Sauvage (mismo local).", sources: ["https://www.barcelona-metropolitan.com/locations/club-sauvage/"] },
  { name: "Arena Classic", reason: "La sala de Diputació ya no existe; su sala Classic sigue dentro de Arena Xperience.", sources: ["https://www.timeout.es/barcelona/es/gay-y-lesbico/arena-xperience"] },
  { name: "Nau B1", reason: "Está en Granollers, no en Barcelona.", sources: ["https://www.songkick.com/venues/1900263-sala-nau-b1-espai-darts-roca-umbert"] },
  { name: "Fira Barcelona Montjuïc", reason: "Sin eventos nocturnos verificados en 2026 (el Sónar 2026 se hace entero en Gran Via).", sources: ["https://www.segre.com/es/cultura/260619/sonar-llena-electronica-recinto-fira-gran-via-barcelona_1247612.html"] },
];
